server:
  port: 8084

spring:
  application:
    name: es-product-search
  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 3s
    socket-timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  elasticsearch:
    index-name: products-v1
