server:
  port: 8083

spring:
  application:
    name: order-kafka-retry-dlq
  datasource:
    url: jdbc:h2:mem:kafka_demo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: order-processing-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.techlab.kafkaretrydlq.domain
        spring.json.value.default.type: com.techlab.kafkaretrydlq.domain.OrderCreatedEvent

app:
  kafka:
    topics:
      order-created: order.created.v1
    retry:
      attempts: 3
      delay-ms: 2000
      multiplier: 2.0

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.techlab.kafkaretrydlq: INFO
    org.springframework.kafka.retrytopic: INFO
